version: "3"

dotenv: [".env"]

tasks:
  init:
    cmds:
      - poetry install
    aliases:
      - i
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc .
      - poetry run mypy scraper
      - poetry run ruff check scraper
      - poetry run ruff format --check scraper
    aliases:
      - l
  lint-diff:
    cmds:
      - poetry run ruff format --diff scraper
    aliases:
      - ld
  format:
    cmds:
      - poetry run black --line-length 80 .
      - poetry run ruff check --fix
    aliases:
      - f
  type-check:
    cmds:
      - poetry run pyrefly check
    aliases:
      - tc
